import { githubConfigured, getAppUser } from "@/auth";
import { ViewerProvider } from "@/components/admin/viewer";
import { Sidebar, type ShellInfo } from "@/components/shell/sidebar";
import { getStore } from "@/lib/server/store";

// Per-viewer (session) and live data: every dashboard page renders on request. In snapshot mode that is an
// in-memory read; with Neon it is what makes promotions and new runs show up immediately.
export const dynamic = "force-dynamic";

export default async function AppLayout({ children }: { children: React.ReactNode }) {
  const store = getStore();
  const [user, generatedAt, alerts, reviews] = await Promise.all([
    getAppUser(),
    store.generatedAt(),
    store.alerts(true),
    store.reviews("pending"),
  ]);
  const info: ShellInfo = {
    mode: store.mode,
    generatedAt,
    user: user ? { name: user.name, login: user.login, role: user.role, image: user.image } : null,
    githubConfigured,
    badges: { "/overview": alerts.length, "/datasets/review": reviews.length },
  };
  return (
    <ViewerProvider viewer={{ role: user?.role ?? "visitor", login: user?.login ?? null, mode: store.mode }}>
    <div className="relative min-h-dvh">
      <div aria-hidden className="pointer-events-none fixed inset-x-0 top-0 h-[520px] bg-[radial-gradient(60%_60%_at_70%_0%,var(--accent-soft),transparent_70%)]" />
      <Sidebar info={info} />
      <main id="main" className="relative lg:pl-[248px]">
        {store.mode === "snapshot" && (
          <div className="border-b border-warn/20 bg-warn-soft/60 px-4 py-2 text-center font-mono text-[0.64rem] tracking-wide text-warn backdrop-blur sm:px-6 lg:px-10">
            Demo mode · synthetic history generated by <code>af-run demo</code>
            {generatedAt ? ` on ${generatedAt.slice(0, 10)}` : ""} — real graders, statistics, attribution and gate on simulated agent behaviour. Read-only.
          </div>
        )}
        <div className="mx-auto w-full max-w-[1480px] px-4 pb-24 pt-6 sm:px-6 lg:px-10 lg:pt-10">{children}</div>
      </main>
    </div>
    </ViewerProvider>
  );
}
