"""Reference numbers for the web app's TypeScript statistics (tests/fixtures/stats_crosscheck.json).

uv run python -m agentforge_runner.stats.crosscheck > tests/fixtures/stats_crosscheck.json
"""

from __future__ import annotations

import json
from typing import Any

from agentforge_runner.stats.intervals import wilson
from agentforge_runner.stats.kappa import calibration_report, cohen_kappa
from agentforge_runner.stats.paired import mcnemar_exact
from agentforge_runner.stats.passk import pass_hat_k

WILSON_CASES = [
    (0, 0),
    (0, 10),
    (10, 10),
    (8, 10),
    (41, 50),
    (1, 50),
    (49, 50),
    (25, 50),
    (7, 30),
    (120, 150),
    (3, 400),
]
MCNEMAR_CASES = [(0, 0), (0, 1), (1, 1), (0, 5), (0, 6), (1, 8), (2, 5), (3, 3), (5, 15), (10, 25), (40, 60)]


def _labels(tp: int, fp: int, fn: int, tn: int) -> tuple[list[bool], list[bool]]:
    """human, judge lists for a confusion table (judge_pass_human_pass, judge_pass_human_fail, …)."""
    human = [True] * tp + [False] * fp + [True] * fn + [False] * tn
    judge = [True] * tp + [True] * fp + [False] * fn + [False] * tn
    return human, judge


KAPPA_TABLES = [(20, 5, 10, 15), (25, 0, 0, 25), (10, 10, 10, 10), (45, 3, 2, 6), (30, 8, 4, 8), (50, 0, 0, 0)]


def build_fixture() -> dict[str, Any]:
    """Shape read by apps/web/tests/stats.test.ts: `wilson`, `mcnemar`, `kappa` lists (+ `pass_hat_k`)."""
    kappa_rows = []
    for tp, fp, fn, tn in KAPPA_TABLES:
        human, judge = _labels(tp, fp, fn, tn)
        k, agreement = cohen_kappa(human, judge)
        rep = calibration_report(human, judge)
        kappa_rows.append(
            {
                "human": human,
                "judge": judge,
                "kappa": round(k, 12),
                "agreement": round(agreement, 12),
                "confusion": rep["confusion"],
                "calibrated": rep["calibrated"],
            }
        )
    return {
        "note": (
            "Generated by agentforge_runner.stats.crosscheck; the web app's lib/stats.ts must reproduce these numbers."
        ),
        "wilson_z": 1.959963984540054,
        "wilson": [
            {"k": k, "n": n, "lo": round(wilson(k, n)[0], 12), "hi": round(wilson(k, n)[1], 12)}
            for k, n in WILSON_CASES
        ],
        "mcnemar": [{"b": b, "c": c, "p": round(mcnemar_exact(b, c), 12)} for b, c in MCNEMAR_CASES],
        "kappa": kappa_rows,
        "pass_hat_k": [
            {"n": n, "c": c, "k": k, "value": round(pass_hat_k(n, c, k), 12)}
            for n, c, k in ((2, 2, 2), (2, 1, 2), (5, 3, 2), (10, 7, 3))
        ],
    }


def main() -> None:
    print(json.dumps(build_fixture(), indent=2))


if __name__ == "__main__":
    main()
