-- AgentForge schema (SPEC §11) for Neon Postgres — applied by apps/web/scripts/migrate.mjs.
-- Additions to the spec are marked "(+)".
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS app_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  github_login text UNIQUE NOT NULL,
  role text NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer','admin')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agents (
  id text PRIMARY KEY,
  repo text NOT NULL,
  adapter_module text NOT NULL,
  optimizable_keys jsonb NOT NULL,
  locked_keys jsonb NOT NULL,
  judge_model text,
  noise_profile jsonb,
  config jsonb,                                  -- (+) workdir, install command, display name, accent
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id text NOT NULL REFERENCES agents(id),
  version int NOT NULL,
  parent_version int,
  body jsonb NOT NULL,
  body_hash text NOT NULL,
  created_by text NOT NULL CHECK (created_by IN ('human','optimizer')),
  experiment_id uuid,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (agent_id, version)
);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_profile ON profiles(agent_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS traces (
  id uuid PRIMARY KEY,
  agent_id text NOT NULL REFERENCES agents(id),
  mode text NOT NULL CHECK (mode IN ('live','eval')),
  run_id uuid, case_id text,
  agent_version text, profile_version text,
  status text NOT NULL,
  started_at timestamptz NOT NULL, ended_at timestamptz,
  input jsonb, final_output jsonb, end_state jsonb,
  spans jsonb NOT NULL,
  metrics jsonb NOT NULL,
  feedback jsonb,
  guard_hit boolean NOT NULL DEFAULT false,
  mined boolean NOT NULL DEFAULT false,
  received_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS traces_agent_time ON traces(agent_id, started_at DESC);
CREATE INDEX IF NOT EXISTS traces_status ON traces(agent_id, status) WHERE mode = 'live';
CREATE INDEX IF NOT EXISTS traces_run ON traces(run_id) WHERE run_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS suites (
  id text PRIMARY KEY,
  agent_id text NOT NULL REFERENCES agents(id),
  kind text NOT NULL CHECK (kind IN ('benchmark','scenario','regression','redteam'))
);

CREATE TABLE IF NOT EXISTS cases (
  id text PRIMARY KEY,
  suite_id text NOT NULL REFERENCES suites(id),
  split text NOT NULL CHECK (split IN ('train','val','test')),
  family text,
  body jsonb NOT NULL,
  content_hash text NOT NULL,
  origin text NOT NULL CHECK (origin IN ('seed','mined','mutation','manual')),
  source_trace_id uuid,
  input_embedding vector(768),
  retired_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cases_suite ON cases(suite_id) WHERE retired_at IS NULL;

CREATE TABLE IF NOT EXISTS suite_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  suite_id text NOT NULL REFERENCES suites(id),
  hash text NOT NULL,
  case_ids text[] NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (suite_id, hash)
);

CREATE TABLE IF NOT EXISTS case_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  draft jsonb NOT NULL,
  cluster_label text,
  source_trace_ids uuid[] NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  reviewer text, reason text, resulting_case_id text,
  created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz
);

CREATE TABLE IF NOT EXISTS runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,  -- (+) human-friendly "Run #412"
  agent_id text NOT NULL REFERENCES agents(id),
  suite_version_ids uuid[] NOT NULL,
  profile_id uuid NOT NULL REFERENCES profiles(id),
  target_ref text NOT NULL,
  trigger text NOT NULL CHECK (trigger IN ('manual','nightly','pr','optimizer','gate')),
  pr_number int,
  experiment_id uuid,
  attempts int NOT NULL DEFAULT 1,
  budget_calls int NOT NULL,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','stalled','done','failed','cancelled')),
  gh_run_id bigint,
  summary jsonb,
  heartbeat_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz
);
CREATE INDEX IF NOT EXISTS runs_agent_time ON runs(agent_id, created_at DESC);

CREATE TABLE IF NOT EXISTS results (
  run_id uuid NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  case_id text NOT NULL REFERENCES cases(id),
  attempt int NOT NULL DEFAULT 1,
  passed boolean,
  status text NOT NULL,
  graders jsonb NOT NULL,
  trace_id uuid,
  block_layer text,
  cost_usd numeric(10,6), latency_ms int, llm_calls int,
  PRIMARY KEY (run_id, case_id, attempt)
);

CREATE TABLE IF NOT EXISTS attacks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seed_case_id text NOT NULL REFERENCES cases(id),
  operator text NOT NULL,
  body jsonb NOT NULL,
  prompt_guard_score real,
  succeeded_in_run uuid,
  promoted_case_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS optimizer_experiments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text,                                     -- (+) 'opt-returnpilot-2026-10-12'
  agent_id text NOT NULL REFERENCES agents(id),
  parent_profile_id uuid NOT NULL REFERENCES profiles(id),
  config jsonb NOT NULL,
  state jsonb,
  calls_used int NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'running' CHECK (status IN ('running','paused','finished','failed','cancelled')),
  best_candidate_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz
);

CREATE TABLE IF NOT EXISTS optimizer_candidates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL REFERENCES optimizer_experiments(id) ON DELETE CASCADE,
  parent_candidate_id uuid,
  label text,                                    -- (+) 'seed', 'c1', 'c2' …
  iteration int,                                 -- (+)
  component text NOT NULL,
  body jsonb NOT NULL,
  rationale text,
  editor_check jsonb NOT NULL,
  minibatch_score real, parent_minibatch_score real,
  val_scores jsonb,
  val_mean real, cost_mean real,
  on_front boolean NOT NULL DEFAULT false,
  status text NOT NULL CHECK (status IN ('rejected_editor','rejected_minibatch','evaluated','gated','promoted')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS promotions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id text NOT NULL REFERENCES agents(id),
  from_profile_id uuid REFERENCES profiles(id),
  to_profile_id uuid NOT NULL REFERENCES profiles(id),
  candidate_id uuid,                             -- (+)
  gate_run_ids uuid[] NOT NULL,
  gate_report jsonb NOT NULL,
  path text CHECK (path IN ('quality','efficiency','rollback','manual')),
  test_attempts int NOT NULL DEFAULT 1,
  decided_by text NOT NULL,
  decision text NOT NULL CHECK (decision IN ('promoted','rejected','pending')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS judge_labels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id text NOT NULL REFERENCES agents(id),
  result_run_id uuid NOT NULL, case_id text NOT NULL, rubric_item text NOT NULL,
  human_verdict boolean NOT NULL, judge_verdict boolean,
  labeler text NOT NULL, accepted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS judge_calibration (
  agent_id text NOT NULL REFERENCES agents(id),
  judge_model text NOT NULL, prompt_hash text NOT NULL,
  n int NOT NULL, kappa real NOT NULL, agreement real NOT NULL,
  confusion jsonb NOT NULL, calibrated boolean NOT NULL,
  computed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (agent_id, judge_model, prompt_hash)
);

CREATE TABLE IF NOT EXISTS llm_usage (
  day date NOT NULL, provider text NOT NULL, model text NOT NULL, purpose text NOT NULL,
  calls int NOT NULL DEFAULT 0, tokens_in bigint NOT NULL DEFAULT 0, tokens_out bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (day, provider, model, purpose)
);

CREATE TABLE IF NOT EXISTS api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL, agent_id text REFERENCES agents(id),
  key_hash text UNIQUE NOT NULL, prefix text NOT NULL,
  scopes text[] NOT NULL,
  last_used_at timestamptz, revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rate_limits (
  key_id uuid NOT NULL, window_start timestamptz NOT NULL, count int NOT NULL DEFAULT 0,
  PRIMARY KEY (key_id, window_start)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id bigserial PRIMARY KEY,
  actor text NOT NULL, action text NOT NULL, object_type text NOT NULL, object_id text,
  details jsonb, at timestamptz NOT NULL DEFAULT now()
);

-- (+) alerts raised by run comparisons (§4.3 step 2) and the scheduler watchdog (§10.2)
CREATE TABLE IF NOT EXISTS alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id text REFERENCES agents(id),
  run_id uuid,
  level text NOT NULL CHECK (level IN ('info','warn','critical')),
  kind text NOT NULL,
  message text NOT NULL,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);
